[package]
name = "allure"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.org>"]
description = "An LR Compiler"

[dependencies]
logos = "0.12"
ariadne = "0.1"
chumsky = "0.8"

[dependencies.clap]
version = "3.1"
features = ["derive"]
